config/routes.rb
Rails.application.routes.draw do

  scope "/:locale" do
    resources :events do
      member do
        get 'vote'
        post 'vote_creat'
        get 'vote_edit'
        post 'vote_update'
        post 'event_result_creat'
      end
    end

    devise_for :users

    root "welcome#index"
  end

  root to: redirect("/#{I18n.locale}"), as: :redirected_root

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :owner, class_name:"User"
  has_one :event_result, dependent: :destroy
  has_and_belongs_to_many :users
  has_many :votes, dependent: :destroy
  accepts_nested_attributes_for :users, allow_destroy: true

  validates :title, length:{minimum: 5}
  validates :iniatial_date, :final_date, :deadline_date, presence:true
  # validate :validate_dates
  # validate :valid_iniatial_date
  # validate :valid_final_date

  def validate_dates
    if deadline_date && deadline_date <= Date.today
      errors.add(:deadline_date, I18n.t(:validate_dates))
    end

    if final_date && final_date <= Date.today
      errors.add(:final_date,  I18n.t(:validate_dates))
    end

    if iniatial_date && iniatial_date <= Date.today
      errors.add(:iniatial_date, I18n.t(:validate_dates))
    end
  end

  def valid_iniatial_date
    if iniatial_date && final_date
      if iniatial_date > final_date
        errors.add(:iniatial_date, I18n.t(:valid_iniatial_date))
      end
    end
  end

  def valid_final_date
    if iniatial_date && deadline_date
      if iniatial_date < deadline_date
        errors.add(:deadline_date, I18n.t(:valid_final_date))
      end
    end
  end
end

app/models/event_result.rb
class EventResult < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :login, length:{minimum: 3}, uniqueness: true

  has_many :owned_events, class_name: "Event", foreign_key: "owner_id", dependent: :destroy
  has_many :votes, dependent: :destroy
  has_and_belongs_to_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :event
  belongs_to :user, autosave:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :login) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :current_password, :login) }
    end

  private

  def user_not_authorized
    flash[:alert] = t(:user_authorized)
    redirect_to(request.referrer || root_path)
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :set_event, only: [:show, :vote, :vote_creat, :vote_edit, :vote_update, :event_result_creat, :edit, :update, :destroy]

  def index
    authorize Event
    if pundit_user
      @events = pundit_user.events
    end
  end

  def show
    authorize @event
    @users = Event.find(params[:id]).users

    voted =  @event.votes

    @percents, @votes = statistics(voted)

    if @event.deadline_date < Date.today
      result = event_result(voted)
      if result.length == 1
        @event.create_event_result(date: result[0])
      end
      if result.length > 1
        @event_result = result
      end

      @show_event_result = @event.event_result
    end
  end

  def vote
    authorize @event

    @dates = @event.iniatial_date..@event.final_date

    @votes = Array.new(@dates.count, Vote.new)
  end

  def vote_creat
    params[:votes].each do |vote|
      new_vote = current_user.votes.new(vote_params(vote))
      new_vote.event_id = @event.id
      new_vote.save
    end
    redirect_to @event
  end

  def vote_edit
    authorize @event

    @votes = Vote.where(user_id: pundit_user.id, event_id: @event.id)
  end

  def vote_update
    params[:votes].each do |key, vote|
      pundit_user.votes.find(key).update(vote_params(vote))
    end
    redirect_to @event
  end

  def new
    @event = Event.new
    authorize @event
  end

  def edit
    authorize @event
  end

  def event_result_creat
    if params[:result_vote].present?
      @event.create_event_result(date: params[:result_vote])
    end
    redirect_to @event
  end

  def create
    @event = pundit_user.owned_events.new(event_params)

    authorize @event

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    authorize @event
    @event.destroy

    redirect_to events_path
  end

  private

  def event_result(voted)
    votes_per_dates = voted.inject(Hash.new(0)) { |h, v| h[v.date] += v.possible_answer; h }
    max_votes = votes_per_dates.values.max

    result = []
    votes_per_dates.each do |date, vote|
      if vote == max_votes
        result << date
      end
    end
    return result
  end

  def statistics(voted)
    votes_per_dates = voted.inject(Hash.new(0)) { |h, v| h[v.date] += v.possible_answer; h }
    max_votes = votes_per_dates.values.max

    percents_per_dates = votes_per_dates.inject(Hash.new) {|h,v| h[v.first] = v.last*100/max_votes; h}

    return percents_per_dates, votes_per_dates
  end

  def vote_params(vote)
    vote.permit(:date, :possible_answer)
  end

  def event_params
    event = params.require(:event).permit(:title, :comment, :deadline_date, :final_date, :iniatial_date, user_ids: [])
    event["user_ids"] << pundit_user.id
    return event
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<br>
<div class="row">
  <div class="small-6 small-centered columns">
    <div class="callout">
      <%= form_for @event do |f| %>
        <% if @event.errors.any? %>
          <div class="callout alert">
            <div id="error_explanation">
              <h3>
                <%= t(:error_event) %>
              </h3>
              <ul>
                <% @event.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <%= f.text_field :title, placeholder:t(:title) %>
        <div class="row">
          <div class="small-6 large-6 columns">
            <%= f.label t(:iniatial_date) %>
            <%= @event.iniatial_date %>
          </div>
          <div class="small-6 large-6 columns">
              <%= f.label t(:final_date) %>
              <%= @event.final_date %>
          </div>
        </div>
        <%= f.label t(:deadline_date_vote)%>
        <%= @event.deadline_date %>
        <%= f.date_field(:deadline_date) %>

        <%= f.select(:user_ids, User.all.where.not(id: current_user.id).map { |user| [user.email, user.id] }, {include_blank: false},{multiple: true} )%>

        <%= f.text_area :comment, placeholder:t(:comment), rows:8 %>

        <%= f.submit t(:save), class:"small secondary hollow button" %>
        <%= link_to t(:back), events_path, class:"small secondary hollow button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<br>
<div class="row">
  <div class="small-10 small-centered columns">
    <% @events.each do |event| %>
      <div class="callout">

        <% if event.deadline_date >= Date.today%>
          <span class="secondary label" style="float:right"> <%= t(:deadline_date_vote) %> <%= event.deadline_date %></span>
        <% else %>
          <span class="alert label" style="float:right"> <%= t(:voting_ended) %> <%= event.deadline_date %></span>
        <% end %>

        <h5><%= event.title %></h5>

        <% if event.comment? %>
          <p><%= truncate(strip_tags(event.comment), length:150) %></p>
        <% end %>

        <% if event.deadline_date < Date.today %>
          <%= link_to t(:show_result), event_path(event), class:"small secondary hollow button"%>
        <% else %>
          <%= link_to t(:show), event_path(event), class:"small secondary hollow button" %>
        <% end %>

        <% if policy(event).edit? %>
          <%= link_to t(:edit), edit_event_path(event), class:"small secondary hollow button" %>
        <% end %>

        <% if policy(event).destroy? %>
          <%= link_to t(:destroy), event_path(event), method: :delete, data: { confirm: 'Are you sure?' },class:"small alert hollow button" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<br>
<div class="row">
  <div class="small-6 small-centered columns">
    <div class="callout">
      <%= form_for @event do |f| %>
        <% if @event.errors.any? %>
          <div class="callout alert">
            <div id="error_explanation">
              <h3>
                <%= t(:error_event) %>
              </h3>
              <ul>
                <% @event.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <%= f.text_field :title, placeholder:t(:title) %>
        <div class="row">
          <div class="small-6 large-6 columns">
            <%= f.label t(:iniatial_date) %>
            <%= f.date_field(:iniatial_date)%>
          </div>
          <div class="small-6 large-6 columns">
            <%= f.label t(:final_date) %>
            <%= f.date_field(:final_date) %>
          </div>
        </div>

        <%= f.label t(:deadline_date_vote) %>
        <%= f.date_field(:deadline_date) %>

        <%= f.select(:user_ids, User.all.where.not(id: current_user.id).map { |user| [user.email, user.id] }, {include_blank: false},{multiple: true} )%>

        <%= f.text_area :comment, placeholder:t(:comment), rows:8 %>

        <%= f.submit t(:save), class:"small secondary hollow button" %>
        <%= link_to t(:back), events_path, class:"small secondary hollow button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<br>
<div class="row">
  <div class="small-10 small-centered columns">
    <div class="row">
      <div class="small-8 large-8 columns">
        <div class="callout">
          <% if @event.deadline_date >= Date.today%>
            <span class="secondary label" style="float:right"> <%= t(:deadline_date_vote) %> <%= @event.deadline_date %></span>
          <% else %>
            <span class="alert label" style="float:right"> <%= t(:voting_ended) %> <%= @event.deadline_date %></span><br>
          <% end %>

          <h3>
            <%= @event.title %>
          </h3>

          <% if @event.comment? %>
            <h5>
              <%= @event.comment %>
            </h5>
          <% end %>

          <p>
            <strong>Final date:</strong>
            <%= @event.final_date %>
          </p>

          <p>
            <strong>Iniatial date:</strong>
            <%= @event.iniatial_date %>
          </p>


          <div class="row">
            <div class="small-12 large-12 columns">

              <% if policy(@event).vote? %>
                <%= link_to t(:vote), vote_event_path, class:"small secondary hollow button" %>
              <% elsif policy(@event).vote_edit?  %>
                <%= link_to t(:change_vote), vote_edit_event_path, class:"small secondary hollow button"%>
              <% end %>
              <%= link_to t(:back), events_path, class:"small secondary hollow button" %>
            </div>
          </div>
        </div>
      </div>

      <div class="small-4 large-4 columns">

        <ul class="accordion" data-accordion data-allow-all-closed="true">
          <li class="accordion-item" data-accordion-item>
            <a class="accordion-title"><%= t(:participants_event) %></a>
            <div class="accordion-content" data-tab-content>
              <% @users.each do |user| %>
                <%= user.login %><br>
              <% end %>
            </div>
          </li>
        </ul>

        <% if policy(@event).admin? %>
          <% if @votes.present? %>
            <ul class="accordion" data-accordion data-allow-all-closed="true">
              <li class="accordion-item" data-accordion-item>
                <a class="accordion-title"><%= t(:statistics_vote) %></a>
                <div class="accordion-content" data-tab-content>
                  <% @votes.each do |date, vote| %>
                    <% if vote != 0 %>
                      <span class="secondary label"><%= date %></span>
                      <div class="success progress" role="progressbar" tabindex="0" aria-valuenow="20" aria-valuemin="0" percent" aria-valuemax="100">
                        <span class="progress-meter" style="width: <%= @percents[date] %>%">
                          <p class="progress-meter-text"><%= t(:voted) %> <%= vote %></p>
                        </span>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </li>
            </ul>
          <% end %>
        <% end %>

        <% if @event.deadline_date < Date.today %>
          <% if @show_event_result.present? %>
            <a class="expanded button success"><%= t(:result_vote)%> <%= @show_event_result.date %></a>
          <% else %>

            <% if @event_result != nil %>
              <% if policy(@event).admin? %>
                <a data-open="exampleModal1" class="expanded button"><%= t(:result_several) %></a>
                <div class="reveal" id="exampleModal1" data-reveal>
                  <h1><%= t(:select_date_event) %></h1>

                  <%= form_tag(event_result_creat_event_path) do %>
                    <% @event_result.each do |vote| %>
                      <%= vote %>
                      <%= radio_button_tag(:result_vote, vote) %>
                      <%= hidden_field_tag(:id, @event.id )%>
                    <% end %>
                    <%= submit_tag 'Subscribe', class:'button'%>
                  <% end %>

                  <button class="close-button" data-close aria-label="Close modal" type="button">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              <% else %>
                <a data-open="exampleModal1" class="expanded button"><%= t(:result_several_expect) %><a>
              <% end %>
            <% end %>

            <% if @event_result == nil %>
              <a class="expanded button alert"><%= t(:no_result)%></a>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/vote.html.erb
<br>
<div class="row">
  <div class="small-10 small-centered columns">
  <%= form_tag vote_creat_event_path do %>
    <div class="callout">
      <div class="row">
        <% @votes.each do |v| %>
          <%= fields_for 'votes[]', v do |vote| %>
            <div class="small-6 large-2 columns end">
              <%= @event.iniatial_date %>
              <%= vote.hidden_field(:date, value: @event.iniatial_date) %>
              <% @event.iniatial_date = @event.iniatial_date + 1.days%>

              <%= vote.select(:possible_answer, [[0], [0.5], [1.0]], {}, {})%>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= submit_tag t(:save), class:"small secondary hollow button" %>
      <%= link_to t(:back), event_path(@event), class:"small secondary hollow button" %>
    </div>
  <% end %>
  </div>
</div>

app/views/events/vote_edit.html.erb
<br>
<div class="row">
  <div class="small-10 small-centered columns">
  <%= form_tag vote_update_event_path do %>
    <div class="callout">
      <div class="row">
        <% @votes.each do |v| %>
          <%= fields_for 'votes[]', v do |vote| %>
            <div class="small-6 large-2 columns end">
              <%= @event.iniatial_date %>
              <%= vote.hidden_field(:date, value: @event.iniatial_date) %>
              <% @event.iniatial_date = @event.iniatial_date + 1.days%>

              <%= vote.select(:possible_answer, [[0], [0.5], [1.0]], {}, {})%>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= submit_tag t(:save), class:"small secondary hollow button" %>
      <%= link_to t(:back), event_path(@event), class:"small secondary hollow button" %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Dey width friends" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div id="responsive-menu">
        <div class="row">
          <div class="small-10 small-centered columns">
            <div class="top-bar-left">
              <ul class="menu">
                <li><%= link_to t(:title_site), root_path, class:"secondary button" %></li>
                <% if pundit_user %>
                  <li><%= link_to t(:events), events_path, class:"secondary hollow button top_bar_button" %></li>
                  <li><%= link_to t(:new_event), new_event_path, class:"secondary hollow button top_bar_button" %></li>
                <% end %>
              </ul>
            </div>
            <div class="top-bar-right">
              <ul class="dropdown menu" data-dropdown-menu>
                <li>
                  <a class="secondary hollow button"><%= I18n.locale %></a>
                  <ul class="menu">
                    <li><%= link_to 'en', root_path("en") %></li>
                    <li><%= link_to 'ru', root_path("ru") %></li>
                    <li><%= link_to 'ua', root_path("ua") %></li>
                  </ul>
                </li>
                <% if pundit_user %>
                  <li><%= link_to t(:edit), edit_user_registration_path,  class:"secondary hollow button top_bar_button" %></li>
                  <li><%= link_to t(:exit), destroy_user_session_path, :method => :delete, class:"secondary hollow button top_bar_button" %></li>
                <% elsif %>
                  <li><%= link_to t(:registration), new_user_registration_path, class:"secondary hollow button top_bar_button"%></li>
                  <li><%= link_to t(:login), new_user_session_path, class:"secondary hollow button top_bar_button"%></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>

    <%= yield %>

  </body>
</html>